<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/css/home.css">

    <title> Suas Informações </title>
    
</head>
<body>
<body>
    <div class="wrapper">
      <nav class="navbar"> 
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Service</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
      </nav>   
    </div>
       
    <form action="login" class= "box" method="POST">
      <h1>Muito Obrigada!</h1>
        <input type="submit" name="Obrigada!" placeholder="Login"></br>
    </form>
    
</body>
</body>
</html>