<!DOCTYPE html>
<html lang="en">     
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../public/css/login.css">
    <title>Login</title>
</head>
<body>
    <form action="home" class= "box" method="POST">
      <h1>Login</h1>
        <input type="text" name="User" placeholder="Ex: @Etec"></br>
        <input type="password" name="Senha" placeholder="Ex: 1234"></br>
        <input type="submit" name="Log" placeholder="Login"></br>
    </form>
</body>
</html>